### ISSUE TITLE
Shiny code is not package compatible

### ISSUE THREAD

**Issue by mhoehle** [Hackout2/incidence#1]
The added shiny code is currently not in a form, which allows it to go in a package. I suggest moving it to either the demo directory or, possibly, somethin like inst/showcase/ or wrap all of it using a function shinyDemo(), which will become part of the package.

**Comment by thibautjombart** [comment]
Agreed. I got this to work for another package. The rational is:
1) put shiny files in inst/xxx
2) create a function starting the server in /R/yyy.R
3) in 2), refer to the files using system.files() 

See example in the adegenet package:
https://sourceforge.net/p/adegenet/code/ci/master/tree/pkg/
Especially:
https://sourceforge.net/p/adegenet/code/ci/master/tree/pkg/R/servers.R

**Comment by rolinavg** [comment]
Ok. I'll give this a shot this evening since all of my code is on my home laptop.

**Comment by thibautjombart** [comment]
Awesome!

**Comment by rolinavg** [comment]
Hopefully the problem is now resolved. I moved the files to the demo directory. Seemed the easiest :)

**Comment by thibautjombart** [comment]
Hi there, 
I get:

``` r
> library(devtools)
> check()
Updating incidence documentation
Loading incidence
Loading required package: ggplot2
Loading required package: network
network: Classes for Relational Data
Version 1.11.3 created on 2014-12-05.
copyright (c) 2005, Carter T. Butts, University of California-Irvine
                    Mark S. Handcock, University of California -- Los Angeles
                    David R. Hunter, Penn State University
                    Martina Morris, University of Washington
                    Skye Bender-deMoll, University of Washington
 For citation information, type citation("network").
 Type help("network-package") to get started.

Loading required package: knitr
 OutbreakTools 0.1-12 has been loaded

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '', probable reason 'No such file or directory'
> 
```

**Comment by thibautjombart** [comment]
Hi Rolina,
I replied on the issue tracking system on github - easier to follow ;)
https://github.com/Hackout2/incidence/issues/1
I still get an error in the check.
Cheers
Thibaut

**Comment by rolinavg** [comment]
hey, 
Initially, I tried moving the files to the demo folder, but they still appeared in the R folder. Then I tried to move them back to the R folder, after creating a new branch called shinyFeatures. On my terminal, it says that I'm now on that branch, but I don't see it on github....hmmmmm....

**Comment by rolinavg** [comment]
rolinavalensmbp:incidence rolinavangaalen$ git status
On branch shinyFeatures
nothing to commit, working directory clean

**Comment by thibautjombart** [comment]
Going through the code. This will not be portable:

``` r
# --- Set working directory
setwd("/Users/rolinavangaalen/Documents/Hackout/time/")
```

And I'm not sure demo can be documented using roxygen, that may be the origin of the problem. Are you happy to let me have a got at it? I'm pretty sure we can package it in inst.

**Comment by rolinavg** [comment]
Of course!

**Comment by rolinavg** [comment]
Once you're done, can you let me know how to update the version on my computer with the one that you'll put on github? Is that a "pull request"?

I've downloaded the github bible, btw. Planning on perusing when I have a spare moment ;)

**Comment by thibautjombart** [comment]
Yes, I don't think you pushed this branch, it is not on origin. Can you push it? 
git push origin shinyFeatures

**Comment by thibautjombart** [comment]
Nice reading indeed ;) Bit geeky, but nice.
Will wait for your pushing the new branch, then give it a go.

**Comment by rolinavg** [comment]
oh! You're right! 'Pushing accomplished'

**Comment by thibautjombart** [comment]
Got it now, thanks. Still can't install the package, but will investigate.
Cheers
Thibaut

**Comment by rolinavg** [comment]
Are the two files still on the master branch? ... as well as the new branch? Could that be causing the problem?

**Comment by thibautjombart** [comment]
Err... I don't understand?
;)

**Comment by thibautjombart** [comment]
Solved. Sort of. Package passes the check. I had to move the .R files to inst, but that is technically a new issue. Will close this one and create a couple of new ones
